export const WorkorderMapEntity = {
  'Request': 'request',
  'Quote': 'quote',
  'WO': 'wo',
  'IO': 'io',
  'Sucursal': 'branch',
  'Supervisor': 'supervisor',
  'Tipo de atención': 'attentionType',
  'Descripción': 'description',
  'BP': 'bp',
  'Cliente': 'client',
  'Equipo': 'equipment',
  'Modelo': 'model',
  'Marca': 'brand',
  'Serie Fábrica': 'fabricSeries',
  'Código SAP': 'sapCode',
  'Estado': 'state',
  'Comentarios': 'comment',
  'F. Requerimiento': 'requirement',
  'F. Llegada': 'arrival',
  'F. Creación WO': 'woCreation',
  'First Labor': 'firstLabor',
  'F. Inicio Plan evaluación': 'evaluationPlanStart',
  'F. Inicio Real evaluación': 'evaluationRealStart',
  'F. Fin Plan evaluación': 'evaluationPlanEnd',
  'F. Fin Real evaluación': 'evaluationRealEnd',
  'F. envío ppto': 'sendingDate',
  'F. aprobación / rechazo ppto': 'receptionDate',
  'Estado ppto': 'budgetState',
  'Estado Prov': 'providerState',
  'F. Inicio Plan prov': 'providerPlanStart',
  'F. Inicio Real prov': 'providerRealStart',
  'F. Fin Plan prov': 'providerPlanEnd',
  'F. Fin Real prov': 'providerRealEnd',
  'Estado Rpts': 'partState',
  'F. Pedido Rpts': 'partSendingDate',
  'F. Plan llegada Rpts': 'partPlanArrival',
  'F. Real llegada de Rpts': 'partRealArrival',
  'F. Inicio Plan reparación': 'repairPlanStart',
  'F. Inicio Real reparación': 'repairRealStart',
  'F. Fin Plan reparación': 'repairPlanEnd',
  'F. Fin Real reparación': 'repairRealEnd',
  'NBD': 'nbd',
  'Motivo cambio por cliente': 'nbdChangingDateReason',
  'Last Labor': 'lastLabor',
  'F. Real de Término': 'realEndDate',
  'Cumplimiento': 'compliance',
  'Motivo': 'motive',
  'Detalle de motivo': 'motiveDetails',
  'F. envío informe': 'reportSendingDate',
  'F. cierre': 'closingDate',
  'F. facturación': 'billingDate',
  'Emergencia': 'emergency',
  'Técnico': 'technician',
  'Bahía': 'bay'
}
