export class TechnicianEntity {
  Lima: string[] = [
    "Patricia Guiliana Moncada Camavilca",
    "Roberto Eduardo Marcelo Gomez",
    "Daniel Alexis Pacheco Gavilan",
    "Jhonny Leobel Breum Astocondor",
    "Miguel Santiago Pariona De La Cruz",
    "Richard Alberto Estrada Izquierdo",
    "Ronal Velasque Huaccaicachacc",
    "Ahilton Rogelio Quispe Toribio",
    "Eduardo Adrian Cuadros Gutierrez",
    "Gino Robert Valenzuela Quispe",
    "Julio Cesar Mamani Checca",
    "Luis Antonio Sosa Espinoza",
    "Noel Manuel Jimenez Valladares",
    "Teodorico Morales Rodriguez",
    "Christiam Rogger Mendoza De Tomas",
    "Cristian Roberht Carlos Montero",
    "Giancarlos Jose Zapata Tuanama",
    "Roberth Edinson Livias Olortegui",
    "Sebastian Moises Llantoy Huaynates",
    "Sergio Tadeo Garcia Bruno",
    "Yurico Milagros Miranda Suyo",
    "Alfredo Wilmer Vasquez Molina",
    "Cesar Alonso Quiquijana Almeyda",
    "Cesar Aurelio Hinojosa Garcia",
    "Hadgler Diego Villavicencio Cerna",
    "John Anderson Guarniz Olortegui",
    "Johnny Giovanni Marca Rivera",
    "Juan Alberto Guevara Sanchez",
  ];
  Arequipa: string[] = [
    "Juan Hernan Alarcon Herencia",
    "Rene Jaime Torres Torres",
    "Jober Jesus Diaz Cusirramos",
    "David Paul Gamero Rosas",
    "Milton Melchor Quispe Chillitupa",
    "Percy Suni Zevallos",
    "Cesar Augusto Gaspar Rosado Guillen",
    "John Andy Diaz Zegarra",
    "Carlos Gustavo Yupanqui Valencia",
    "Julio Victor Begazo Chavez",
    "Ricardo Nilo Chambi Chambi",
    "Jorge Leonidas Calla Mamani",
    "Cesar Halanocca Ticona",
    "Victor Raul Hancco Cruz",
    "Juan Carlos Linares Bedoya",
    "Wilver Huillca Panti",
    "Carlos Enrique Flores Rodriguez",
    "Efrain Wilbert Palma Cayani",
    "Carlos Marcelo Javier Condori",
    "Carlos Guillermo Mongrut Perez",
    "Dimas Dante Acuña Velasquez",
    "Ericcson Javier Gil Cazani",
    "Cesar Anyhelot Alvarado Moron",
    "Kentsu Christian Lam Molleapaza",
    "Richard Jose Mamani Arcana",
    "Luis Alfredo Quispe Conislla",
    "Omar Alonso Peralta Mier",
    "Sergio Jhonatan Alvarado Ballenas",
    "Fortunato Wilder Conchucos Leandro",
    "Henrry Wily Cruz Sarayasi",
    "Alexander Laura Layme",
    "Juan Carlos Navarro Huancollo",
    "Luis Simon Puma Mayta",
    "Lindolfo David Ticona Arqque",
    "Alexander Michel Villanueva Idme",
    "William Faus Zuñiga Mamani",
    "Ludwig Balduino Condori Auquilla",
    "Cesar Figueroa Ccalla",
    "Jose Miguel Coaquira Panca",
    "Jose Luis Valdivia Valeriano",
    "Juan Carlos Mamani Mayhua",
    "Edgar Diego Huallpa Ito",
    "Marco Antonio Umpire Linares",
    "Miguel Angel Medina Flores",
    "Andy Daniel Vasquez Lino",
    "Richard Romel Rios Rojas",
    "Angel Challa Charccahuana",
    "Edison Erick Chilo Taco",
    "Enrique Renzo Salazar Valdivia",
    "Frank Eufracio Apaza Mamani",
    "Ernesto Cano Villafuerte",
    "Ulises David Palomino Gallegos",
    "Raul Enrique Vargas Salamanca",
    "Marco Antonio Gonzales Nuñez",
    "Julio Cesar Bejarano Yacolca",
    "Jhon Diego Herrera Pinto",
    "Jhosmer Quispe Ampuero",
    "Chano Vargas Ochoa",
    "Edwar David Huamani Calcina",
    "Luis Angel Paja Jara",
    "Javier Cabanillas Arevalo",
    "Paul Jesus Torres Torres",
    "Edwin Jose Chambi Mestas",
    "Nicolas Hidelgardo Delgado Sanchez",
    "Alex Sandro Quispe Cardeña",
    "Ronal Noe Mucho Yancapallo",
    "Edi Alber Quispe Ancco",
    "Deyvid Antonio Gonzales Quiroz",
    "Jhoan Jhonny Payhua Yance",
    "Emilio Humberto Silva Roque",
    "Adolfo Condori Luna",
    "Isaul Laures Ramos Perez",
    "Jose Carlos Mullisaca Vilca",
    "Cirilo Felipe Cayllahua Ollachica",
    "Josue Willians Condori Auquilla",
    "Nicanor Guillermo Roca Cayra",
    "Juan De Dios Huamani Zaa",
    "Darwin Alberto Dongo Chavez",
    "Luis Miguel Paco Choque",
    "Ximena Belen Quispe Menendez",
    "Edwin Alexander Flores Condori",
    "Johnny Roger Umiyauri Chino",
    "Gualberto Cristobal Cahuana Palacios",
    "Edgar Daniel Flores Rodriguez",
    "Marco Antonio Lipa Mamani",
    "Damian Olguin Callo Tapada",
    "Neikel Arthur Lee Apaza Morales",
    "Rudy Franz Ramos Llanos",
    "Gregorio Alberto Pinedo Pari",
    "Alexander Sancho Coaquira",
    "Raul Quispe Tizon",
    "Cesar Manuel Chun Murguia",
    "Victor Alfonso Condori Quispe",
    "Jonathan Wilfredo Rodriguez Ayala",
    "Jorge Luis Carrillo Hugo",
    "Wilber Cristhian Vita Sisihua",
    "Richard Antonio Caceres Solorzano",
    "Rolando David Vilca Mamani",
    "Giovanni Giancarlo Velasquez Alegre",
    "Jose Fernando Atajo Callata",
    "David Federico Merma Valeriano",
    "Edwar Curis Mayhua",
    "Fredy Poma Torres",
  ];
  Cajamarca: string[] = [
    "Guillermo Chilon Ramos",
    "Juan Raul Cueva Mendoza",
    "Denys Yini Guerrero Cabrejos",
    "Jose Alberto Gallo Ramirez",
    "Carlos Fernando Arteaga Chavez",
    "Romer Enrique Cubas Sanchez",
    "Igor Moises Hernandez Solis",
    "Ricardo Wilmer Tejeda Salazar",
    "Jorge Oswaldo Alvaro Cachi",
    "Marco Martin Celis Sanchez",
    "Segundo Rafael Correa Becerra",
    "Juan Carlos Quispitongo Mantilla",
    "Jose Luis Chilon Yopla",
    "Angel Infante Llanos",
    "Gelber Ronal Chuquilin Fernandez",
    "Luis Alberto Rojas Pomatanta",
    "Jim Tony Espiritu Escalante",
    "Wildo Rafael Campos",
    "Jose Marcelino Requelme Ocas",
    "Luis Gonsaga Garcia Guevara",
    "Victor Manuel Medina Paredes",
    "Luis Fernando Bacon Idrugo",
    "Segundo Ramiro Villanueva Zona",
    "Nelson Cholan Linares",
    "Marlon Paul Silupu Carhuatanta",
    "Jose Luis Huayhua Machaca",
    "Pablo Saavedra Huaman",
    "Wener Espinoza Pereyra",
    "Manuel Marco Antonio Salazar Soto",
    "Jaime Lozano Cerdan",
    "Javier Malca Ruiton",
    "Deyner Eduar Gaona Rodriguez",
    "Dick Henry Chinchay Zelada",
    "Raling Estuardo Medina Arteaga",
    "Omar Chilon Marcelo",
    "Esteban Tello Corteaga",
    "Jorge Flores Castrejon",
    "Carlos Tejada Libaque",
    "Cesar Carrasco Aquino",
    "Alberto Jhonatan Briones Arribasplata",
    "Hernan Gonzalo Guarniz Mendoza",
    "Edgar Alfredo Lopez Ramirez",
    "Gilmer Castañeda Tirado",
    "Fernando Zelada Bobadilla",
    "Segundo Orlando Lozano Peralta",
    "Franklin Fabian Tirado Ruiz",
    "Antonio Saman Mendoza",
    "Elio Lozano Tejada",
    "Miguel Eduardo Chacon Ocas",
    "Segundo Francisco Ocas Huaripata",
    "Eloy Huatay Diaz",
    "Ecuar Eduard Cueva Infante",
    "Carlos Enmanuel Pisco Mendoza",
    "Luis Alberto Portal Sangay",
    "Idelso Campos Acuña",
    "Juan Carlos Flores Jordan",
    "Manuel Enrique Sanchez Sandoval",
    "Osval Ruben Izquierdo Castañeda",
    "Wilmer Terrones Huaman",
    "Haylers Valenzuela Gavidia",
    "Eduardo Chilon Gonzales",
    "Segundo Alvarito Cerquin Quispe",
    "Walter Alberto Villanueva Quispe",
    "Luis Alberto Alcantara Mendoza",
    "Amner Enrriquez Quenema",
    "Percy Huaman Chalan",
    "Pablo Cesar Verastegui Hernandez",
    "Nilton Eli Benavides Chavez",
    "Shimy Jhorch Vergara Reaño",
    "Almilcar Limay Tantalean",
    "Carlos Alberto Goicochea Tirado",
    "Ricardo Enrique Wong Leon",
    "Brando Hugo Clavo Fernandez",
    "Derik Eduardo Telles Vigo",
    "Antonio Medina Zamora",
    "Jean Carlos Montenegro Bereche",
    "Willy David Chavarri Teran",
    "Luis Humberto Sandoval Rosas",
    "Frank Danilo Portal Quiroz",
    "Helber Vidal Maguiña Franco",
    "Agustin Carmona Bobadilla",
    "Fred Ronal Calua Bringas",
    "Elmer Cortez Huatay",
    "Noe Fernandez Aquino",
    "Roger Ivan Arce Chavez",
    "Yordi Ladislao Pichen Diaz",
    "Emilio Elias Huaripata Chacon",
    "Joel Herrera Irigoin",
    "Jorge Alexander Pita Lezma",
    "Jheison David Mancilla Rodrigo",
    "Jhony Raul Vasquez Goicochea",
    "Luis Enrique Huaringa Jurado",
    "Ulises Ernesto Sangay Infante",
    "Jorge Chavez Bautista",
    "Eliseo Pablo Villanueva Roncal",
    "Richard Chavez Ramirez",
    "Gerson Rubio Martinez",
  ];
  Cusco: string[] = [
    "Richard Emmerson Vergaray Espiritu",
    "Nelson Manuel Alcantara Terrones",
    "Miguel Angel Escobar Mendoza",
    "Jerkenson Aldo Tito Tito",
    "Alfredo Martin Velarde Sanchez",
    "Reli Pacheco Urquizo",
    "Jaime Ttupa Huaman",
    "Job Esteban Conde Arce",
    "Juan Jose Fuentes Prudencio",
    "Frank Gustavo Puchoc Espejo",
    "Michael Palomino Guillen",
    "Jafet Ficol Del Aguila Panduro",
    "Nelzon Sivincha Oviedo",
    "Jimmy Darwin Ramirez Farias",
    "Manuel Ramiro Escobedo Serrano",
    "Gararin Dante Cubas Sanchez",
    "Broom Michael Cruz Charaja",
    "Guillermo Mamani Quispe",
    "Miguel Pusaclla Gonzales",
    "Antony Alberto Peralta Gima",
    "Eberth Sinchi Huaman",
    "Jose Luis Aroni Chunga",
    "Richar Quispe Chuco",
    "Luis Alberto Pauccar Pañihuara",
    "Gary Paul Machicao Apaza",
    "Alfredo Baca Oros",
    "Jhonatan Cruz Puma",
    "Julio Cesar Carpio Orosco",
  ];
  Huancayo: string[] = [
    "Jhon Charles Cerron Nastares",
    "Frank Jhon Pascual Lopez",
    "Roberto Carlos Ramos Madrid",
    "Erik Galarza Sovero",
    "Simon Fidel Ninahuanca Quispe",
    "Claudio Francisco Sullcaray Ccama",
    "Lener Arturo Robles Rivera",
    "Beto Jershon Felix Perales",
    "Segundino Teobaldo Feliciano Miguel",
    "Alberson Vargas Robles",
    "Jhoel Marciano Gomez Vidal",
    "Jorge Luis Larzo Isidro",
    "Henry Richard Huaman Limaco",
  ];
  Trujillo: string[] = [
    "Alexis Arnold Ruiz Rojas",
    "Jose Luis Linares Aguilar",
    "Junior Manuel Medina Cueva",
    "Dennys Jhovany Vargas Caceda",
    "Wilfredo Saul Mercedes Ybañez",
    "Hernan Rossi Paredes Principe",
    "Evin Luis Zavaleta Ulloa",
    "Henry Edward Abanto Huaman",
    "Wilmer Manuel Cerquin Ocas",
    "Anthony Alexander Anticona Gamboa",
    "Marlon Hayden Pacheco Miranda",
    "Cristhian Leonardo Valverde Rafael",
    "Yonatan Luis Haro Perez",
    "Nilser Anover Villegas Contreras",
    "Jose Luis Ortega Patricio",
    "Elvis Victoriano Vasquez Quispe",
    "Jhon Jairo Guarniz Cosamalon",
    "Victor Jeancarlo Vasquez Castro",
    "Martin Joel Esquivel Bellodas",
    "Edwin Roy Lizarraga Gomez",
    "Jose Darlin Rodriguez Chavez",
    "Jonathan Antony Campos Sanchez",
    "Edwin Adelyn Trujillo Quiroz",
    "Yeri Ramirez Espinoza",
  ];
  Lambayeque: string[] = [
    "Daniel Zuñiga Acosta",
    "Fernando Sanchez Olortegui",
    "Juan Francisco Cepeda Obando",
    "Javier Zeña Valdera",
    "Jorge Luis Chapoñan Peche",
    "Joel Merino Peña",
  ];
  Ilo: string[] = [
    "Henry Guillermo Colque Quispe",
    "Abel Eugenio Tara Torres",
    "Alberto Rafael Montalvo Cruz",
    "Nelson Alex Salazar Rios",
    "Paolo Cesar Valdivia Lucana",
    "Saul Diego Apaza Vilca",
    "Wilber Mayta Condori",
    "Abel Boris Apaza Vilca",
    "Enrique Miguel Miranda Mollenedo",
    "Yony Juan Catacora Llanque",
    "Richard Zapata Mamani",
    "Jose Mauricio Huamani Flores",
    "Julio Cesar Chipana Paucar",
    "Marquinho Arian Garcia Berrios",
    "Ruben Nicolas Vidaurre Bances",
    "Yulissa Milagros Cama Maron",
    "Keddy Omar Yupanqui Condori",
    "Victor Hugo Rodriguez Diaz",
    "Juan Manuel Romero Salas",
    "Erick Cristhian Zapata Mamani",
  ];
  Piura: string[] = [
    "Hermogenes Espinoza Lozano",
    "Porfirio Otero Peralta",
    "Julio Cesar Ayosa Panta",
    "William Nizama More",
    "Manuel Muñoz Loja",
    "Jhyxon Hamer Quinde Marchena",
    "Luis Alfredo Caicedo Atencio",
    "Marco Antonio Sernaque Herrera",
    "Ronaldo Censinii Risco Pusma",
    "Elky Arturo Gamonal Torres",
    "Pedro Javier Peralta Gallo",
    "Jesus David Juarez Lejabo",
    "Denilson Smix Ramos Elias",
  ];
  
}
